name: 'Setup ddev'
description: 'Set up your GitHub Actions workflow with ddev '
author: 'Jonas Eberle'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: cpu
  color: yellow
inputs:
  ddevDir:
    description: 'ddev project directory'
    required: false
    default: '.'
  autostart:
    description: 'Start ddev automatically'
    required: false
    default: true
